# Generated by Django 4.2.30 on 2026-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('booking_date', models.DateField()),
                ('service', models.CharField(choices=[('Bridal Mehndi', 'Bridal Mehndi'), ('Arabic Mehndi', 'Arabic Mehndi'), ('Modern Mehndi', 'Modern Mehndi')], max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
