# Generated by Django 4.2.30 on 2026-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
