# Generated by Django 4.2.30 on 2026-07-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_review_alter_contact_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Private note visible only to administrators.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Optional note or special requirement from the customer.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_confirmation_sent',
            field=models.BooleanField(default=False, help_text='Shows whether the booking confirmation email was sent.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='receipt_generated',
            field=models.BooleanField(default=False, help_text='Shows whether the booking receipt was generated.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Optional reply or internal response note.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark the contact message as read.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers will appear first.'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured reviews can be displayed first.'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers will appear first.'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='client_type',
            field=models.CharField(blank=True, help_text='Example: Bridal Client or Engagement Client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='website_boo_booking_119dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='website_boo_booking_b282cb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='website_boo_status_8f67dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['phone'], name='website_boo_phone_bb66a4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='website_boo_created_9e9a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='website_boo_booking_109794_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_read'], name='website_con_is_read_49192b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='website_con_created_b36bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='website_con_email_a16188_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_visible', 'display_order'], name='website_gal_is_visi_a34539_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_visible', 'is_featured'], name='website_rev_is_visi_edf2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='website_rev_rating_3b3faf_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_available', 'display_order'], name='website_ser_is_avai_db056f_idx'),
        ),
    ]
