# Generated by Django 4.2.30 on 2026-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_booking_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_booking_119dcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_booking_b282cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_status_8f67dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_phone_bb66a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_created_9e9a0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='website_boo_booking_109794_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='website_con_is_read_49192b_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='website_con_created_b36bc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='website_con_email_a16188_idx',
        ),
        migrations.RemoveIndex(
            model_name='gallery',
            name='website_gal_is_visi_a34539_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='website_ser_is_avai_db056f_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_note',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email_confirmation_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email_confirmation_sent_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='receipt_generated',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Bridal Mehndi', 'Bridal Mehndi'), ('Arabic Mehndi', 'Arabic Mehndi'), ('Modern Mehndi', 'Modern Mehndi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
